"""
OpenKeywords - SE Ranking Gap Analysis Example

SE Ranking finds keywords your competitors rank for but you don't,
filtered for AEO (Answer Engine Optimization) potential.

Before running, set your API keys:
    export GEMINI_API_KEY='your-gemini-api-key'
    export SERANKING_API_KEY='your-seranking-api-key'

Run from project root:
    python examples/with_seranking.py
"""

import asyncio
import os

from openkeywords import KeywordGenerator, CompanyInfo, GenerationConfig


async def main():
    if not os.getenv("GEMINI_API_KEY"):
        print("Error: Set GEMINI_API_KEY environment variable")
        return

    has_seranking = bool(os.getenv("SERANKING_API_KEY"))
    if not has_seranking:
        print("Note: SERANKING_API_KEY not set - gap analysis will be skipped")
        print("Keywords will be generated by AI only.\n")

    generator = KeywordGenerator()

    company = CompanyInfo(
        name="FitnessPro",
        url="https://fitnesspro.com",
        industry="Health & Fitness",
        description="Online fitness coaching and workout programs",
        services=["personal training", "nutrition coaching", "workout plans"],
        products=["FitnessPro App", "Meal Plans"],
        target_audience="health-conscious adults",
        target_location="United States",
        competitors=["myfitnesspal.com", "noom.com"],
    )

    config = GenerationConfig(
        target_count=50,
        min_score=40,
        enable_clustering=True,
        cluster_count=6,
        language="english",
        region="us",
    )

    print(f"Generating keywords for {company.name}...")
    print(f"URL: {company.url}")
    print(f"SE Ranking gap analysis: {'enabled' if has_seranking else 'disabled'}")

    result = await generator.generate(company, config)

    print(f"Generated {len(result.keywords)} keywords in {result.processing_time_seconds:.1f}s")
    print(f"Average score: {result.statistics.avg_score:.1f}")

    print("\nTop Keywords with Metrics:")
    for kw in result.keywords[:15]:
        print(
            f"{kw.keyword:<45} | {kw.intent:<12} | {kw.score:>5} | {kw.volume:>7} | {kw.difficulty:>4}"
        )

    result.to_csv("keywords_with_gaps.csv")
    result.to_json("keywords_with_gaps.json")


if __name__ == "__main__":
    asyncio.run(main())
